eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
server:
   port: 8761
spring:
  application:
    name: eureka-registry    
zuul:
  prefix: /api
  routes:
    service2:
     path: /service2/**
     url: http://localhost:8762
    service3:
     path: /service3/**
     url: http://localhost:8763 