apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
        version: "v1"
    spec:
      containers:
        - name: gateway
          image: 'gcr.io/pockubernetes-276221/gateway:v1'
          ports:
            - containerPort: 8080
        - name: service2
          image: 'gcr.io/pockubernetes-276221/service2:v2'
          ports:
            - containerPort: 8762
        - name: service3
          image: 'gcr.io/pockubernetes-276221/service3:v2'
          ports:
            - containerPort: 8763
        - name: serviceregister
          image: 'gcr.io/pockubernetes-276221/serviceregister:v1'
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway
  type: LoadBalancer