eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true   
spring:
   application:
      name: service2
server:
  port: 8762    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream